### PR TITLE
Use readline instead of undocumented APIs

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by helloIAmPau** [comment]
Hi @brycekahle, thank you for your pr.

There are two issues here that we should discuss in order to accept your changes:
1) readline must be closed to allow the main program a clean exit
2) readline is part of node from v.10. node-spinner has as min version v.8

If you fix 1) and you explain me what kind of improvement we can gain by using readline, maybe I can accept your pr and update the min version for the project.

**Comment by brycekahle** [comment]
`readline` only has to be closed if you use `createInterface`, which I am not. This change fixes the following exception if you try to pipe the output to another program like `grep`.

```
node_modules/cli-spinner/index.js:89
process.stdout.clearLine();
^
TypeError: Object #<Socket> has no method 'clearLine'
at clearLine (/xxx/node_modules/cli-spinner/index.js:89:20)
at null.<anonymous> (/xxx/node_modules/cli-spinner/index.js:47:5)
at wrapper [as _onTimeout] (timers.js:261:14)
at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by helloIAmPau** [comment]
@brycekahle thank you for the bug report. I will merge your pr asap.

ps spark is a really cool project!

**Comment by brycekahle** [comment]
@helloIAmPau Could you publish a new version to NPM? Thanks!

**Comment by brycekahle** [comment]
Nevermind you did! Thanks!

**Pull request merged**
