### PR TITLE
Add ability to pass a stream to use for writing.

### PR DESCRIPTION
**Pull request by sixcircuit**
Thanks for the great library. I wanted to use stderr for the spinner, so I made some changes you might be interested in merging upstream.

"add options object, make onTick an instance variable, add option to pass a stream to use for writing, make clearLine an instance method."

I can update the documentation if you're interested in merging.

### CODE REVIEW

**Comment by helloIAmPau** [comment]
It looks like a great idea.
I merge your code as soon as you complete your MR by updating the documentation.

Thanks a lot for your time :D

**Comment by sktaylor** [comment]
I updated the documentation. It's the best I could make it look. I also added myself as a contributor in the package.json.

**Comment by sktaylor** [comment]
Also, my bad. I just realized I should have squashed these. New workflow for me.

**Comment by chay22** [comment]
Any update on this? Passing options is good since mostly the whole method names are quite long :p

**Comment by jjdonov** [comment]
@helloIAmPau  I'm interested in using your module but would need this PR (or similar) merged first. Is there anything holding this up?

**Comment by helloIAmPau** [comment]
Uh, I didn't see all this hype about this feature.. sorry for the delay. I'll update the packet during the weekend (Irish weekend). I hope is OK for you.

**Pull request merged**
